### ISSUE TITLE
Add post_deploy example to the .magento.app.yaml file

### ISSUE THREAD

**Issue by hostep** [magento/magento-cloud#164]
Hi guys!

I was looking for information around how we should setup then new post_deploy hook which was introduced in ece-tools v2002.0.10 and I couldn't find it in the changelog for the ece-tools, so I started by looking here, since I assumed it would be here, but it isn't unfortunately.

After some more searching around, I did find it on the devdocs: http://devdocs.magento.com/guides/v2.2/cloud/project/project-conf-files_magento-app.html

But I think it should be added to this project as well?

----

Slightly related, it looks like we have a new binary now `./vendor/bin/ece-tools`, and I think it can be used for the build and deploy hooks as well. If that's true, it might make sense to make these hooks in this project consistent so it looks clean (and also do the same thing in the documentation)

-----

*Update*: and just found another config missing, in the .magento.env.yaml file, it currently doesn't contain the post-deploy configuration, which can be found over here at the devdocs: http://devdocs.magento.com/guides/v2.2/cloud/env/variables-post-deploy.html

*Update 2*: also the `SKIP_HTML_MINIFICATION` example doesn't exist yet in this project, see docs again: http://devdocs.magento.com/guides/v2.2/cloud/env/variables-intro.html#skip_html_minification
It might be possible that other examples are also missing, but I'm going to stop looking for these now 😉 

Thanks!

**Comment by shiftedreality** [comment]
Thanks @hostep 

I created ticket MAGECLOUD-2072 to add post-deploy hook.
We have an internal task to update all environment variables in the template MAGECLOUD-1908

**Comment by shiftedreality** [comment]
Changes regarding correct hooks were merged.

**Comment by YPyltiai** [comment]
@hguthrie , please fix DevDocs examples of hooks (https://devdocs.magento.com/guides/v2.2/cloud/project/project-conf-files_magento-app.html#hooks) to be aligned with https://github.com/magento/magento-cloud/blob/master/.magento.app.yaml#L73-L82

Once fixed, this request can be marked as completed.

Thanks!

**Comment by hguthrie** [comment]
Updated the hooks samples in the Cloud guide. Per @YPyltiai , this can be closed.

**Comment by hostep** [comment]
I don't agree with closing this issue just yet, my third remark hasn't been fixed yet. The `.magento.env.yaml` file in this repo still misses certain example configurations, for example:
- `SKIP_HTML_MINIFICATION`
- `MYSQL_USE_SLAVE_CONNECTION`
- `REDIS_USE_SLAVE_CONNECTION`
- `WARM_UP_PAGES`
-  ...

**Comment by YPyltiai** [comment]
@hostep , this cannot be included into template anymore. In latest ECE-Tools to be released `2002.0.12` this file will be extracted from ECE-Tools during composer update process (sample file). It will have all the up to date variables with additional documentation, specified defaults & expected values. This was re-worked, so we can better maintain this file up to date. After `2002.0.12` this file from `magento-cloud` repo will be removed

**Comment by shiftedreality** [comment]
Closed
