### ISSUE TITLE
"source .bashrc" Operation is not goes normal

### ISSUE THREAD

**Issue by michaeldyl520** [magento/magento-cloud#20]
Steps to reproduce
--
1. curl -sS https://accounts.magento.cloud/cli/installer | php
2. source ~/.bashrc

Expected result
do next
magento_cloud

Actual result
can not do next ,"source .bashrc" Operation is not goes normal
cpu use more than 20%

How can I resolve this problem?

**Comment by michaeldyl520** [comment]
I resolve by myself,the version 1.4.0 of magento_cloud possible have some run ,so I rollback to 1.3.0,this is the magento-cloud 1.3.0 url https://accounts.magento.cloud/sites/default/files/magento-cloud-v1.3.0.phar,download it,and chmod +x magento-cloud-v1.3.0.phar,then we can execute it.

**Comment by YPyltiai** [comment]
Hi @michaeldyl520,

Is it still an issue for you?

Thanks,
Yevhenii
