### ISSUE TITLE
The system cannot find the file specified. auth.json.sample

### ISSUE THREAD

**Issue by itsazzad** [magento/magento-cloud#297]
Where is auth.json.sample?

**Comment by shiftedreality** [comment]
It's still in `README.doc` and https://devdocs.magento.com/guides/v2.0/cloud/setup/first-time-setup-import-prepare.html#auth-json
```
{
"http-basic": {
   "repo.magento.com": {
      "username": "<public-key>",
      "password": "<private-key>"
    }
}
```

**Comment by shiftedreality** [comment]
Corresponding PR https://github.com/magento/magento-cloud/pull/299

**Comment by shiftedreality** [comment]
PR was merged, closed.
