### ISSUE TITLE
composer install aborted

### ISSUE THREAD

**Issue by itsazzad** [magento/magento-cloud#298]
On `composer install --ignore-platform-reqs`
```
[Composer\Downloader\TransportException]     
Invalid credentials for 'https://repo.magento.com/archives/magento/module-worldpay/magento-module-worldpay-100.2.3.0.zip', aborting. 
```
Is that related with the structure of auth.json file stated in https://github.com/magento/magento-cloud/issues/297

**Comment by shiftedreality** [comment]
In most cases, this means that your creds in `auth.json` are missing or invalid. Please, check them and reopen this ticket if it does not solves your error.
Closed.

**Comment by protzi** [comment]
@shiftedreality have save issue
Here is structure
<img width="327" alt="screen shot 2019-02-07 at 3 44 27 pm" src="https://user-images.githubusercontent.com/17887536/52415311-50a43580-2aef-11e9-8f9d-b11f4413c3a3.png">
and in `auth.json`
```
{
  "http-basic": {
    "repo.magento.com": {
      "username": "57b01ee862ca*******e3566de444490",
      "password": "6f692151d7a5d*******483fbadcd8da"
    }
  }
}
```
r

**Comment by mrzaizai2233** [comment]
Was you fixed it.I also met same issue

**Comment by shiftedreality** [comment]
Magento Cloud requires your keys to have access to EE packages. It won’t install with regular CE keys.

**Comment by reena-vaimo** [comment]
Why is this issue closed when there is no solution provided in it ?
