### ISSUE TITLE
How to install require-dev modules from magento2

### ISSUE THREAD

**Issue by jordanvector** [magento/magento-cloud#404]
How do we install the magento testing framework with magento cloud?  the only reference that I have seen in the docs is to switch the magento2 repo to the develop branch, but how do we do that with magento cloud?

I guess we could manually go pull those requirements from the magento2 repo.

**Comment by melonmonster** [comment]
@jordanvector At the moment, you either need to install the all dependencies manually ( see [here](https://github.com/magento/magento-cloud/pull/337) as a reference. Note: I have to update this PR, but the basic idea is there... you need to do it all manually ), or install the various dependencies as global composer requirements on the desired, non-Cloud, environment; or install the dependencies as phar files ( again, on the non-Cloud environment ).

**Comment by gamort** [comment]
Or you change your build hooks.  Instead of
    build: |
        set -e
        php ./vendor/bin/ece-tools build:generate
        php ./vendor/bin/ece-tools build:transfer

Use
    build: |
        set -e
        composer install
        php ./vendor/bin/ece-tools build:generate
        php ./vendor/bin/ece-tools build:transfer

That will install all the "dev" extensions which did not get installed with the first "composer install --no-dev" BEFORE anything else is executed.  And it will skip everything that was already installed.
