### ISSUE TITLE
Problem during composer install with magento/module-invitation

### ISSUE THREAD

**Issue by frachello89** [magento/magento-cloud#407]
Hello,
I need to install magento2 cloud on a new machine but when I do it after a while it gives me the error:

  - Installing magento/module-invitation (100.3.3): Downloading (connecting...)
In RemoteFilesystem.php line 673:
                                                                                                                                            
  Invalid credentials for 'https://repo.magento.com/archives/magento/module-invitation/magento-module-invitation-100.3.3.0.zip', aborting.  
                    
Obviously I do not get this error on my machine when I try to reproduce the problem because it loads the module from cache.
I'm looking forward for your kind reply.
Thank you

**Comment by YPyltiai** [comment]
@frachello89 , you need to check your composer keys. It looks like you have no access to repo.magento.com

**Comment by frachello89** [comment]
> @frachello89 , you need to check your composer keys. It looks like you have no access to repo.magento.com

hello @YPyltiai I can confirm that it is not so, for these reasons:
1) I can login at https://account.magento.com/, click on Marketplace and then on Access Keys I found the keys (private and public) that I already generated (and that I used to install magento2 the first time)
2) I asked to other 2 persons that have they own keys (and that they use without any problem) and using them keys too the problem is still here
3) other magento's modules (like for example magento/module-indexer (100.3.3): Downloading (100%) 
 or magento/module-catalog-url-rewrite (100.3.3): Downloading (100%)) are installed correctly

**Comment by YPyltiai** [comment]
@frachello89 the modules you mentioned which download correctly are from Open Source version (not Commerce), so they don't need Commerce access and thus may work even with not enabled for Commerce keys.

To check what is wrong we may need a ticket to Zendesk, please. You will need to provide your MageID there, so we can check if all the entitlements are correct.

**Comment by frachello89** [comment]
@YPyltiai ok, have I to open that ticket? if yes in which way? otherwise if you do it, in which way I give you my Mage ID?
Thank you!

**Comment by YPyltiai** [comment]
@frachello89 you or someone from your team who has access needs to do that through https://support.magento.com/ . If you have a Cloud project, you should have access to Support portal if you follow the link.

**Comment by SayB** [comment]
hey @frachello89 - did you ever git this resolved? I'm also running into this. And so far I've confirmed my keys are okay. 
You see, if auth keys are problem, then it shouldn't download other modules too. Which it does.

**Comment by frachello89** [comment]
Hello @SayB my problem we’re auth keys, indeed changed them my problem was solved. Many of the modules installed correctly in my case before it gave me the error, probably my old keys had not enough permissions...

**Comment by frachello89** [comment]
Feel free to reopen my ticket if you are sure that your keys are really ok and issue is still present!

**Comment by hirensoni2005** [comment]
Hey, I am also facing the same issue while setting up Magento cloud. 
- I have configured SSH key
- Tried with regenerating public-private key

`Package operations: 371 installs, 0 updates, 0 removals
  - Installing magento/module-invitation (100.3.5): Downloading
                                                                                                                                          
  [Composer\Downloader\TransportException]                                                                                                
  The 'https://repo.magento.com/archives/magento/module-invitation/magento-module-invitation-100.3.5.0.zip' URL required authentication.  
  You must be using the interactive console to authenticate `
