### ISSUE TITLE
When 2.3.4 will be out? 

### ISSUE THREAD

**Issue by alexblueacorn** [magento/magento-cloud#408]
I can't do 2.3.4 upgrade, this module breaks it.

![Screen Shot 2020-01-15 at 10 39 48 AM](https://user-images.githubusercontent.com/40637919/72447464-5f757c80-3783-11ea-87f7-0b69591922ac.png)

**Comment by andriyShevtsov** [comment]
it was 6 hour ago. Right now it's fully released. Please try again

**Comment by alexblueacorn** [comment]
Yeah, it works now. Thanks.
