### ISSUE TITLE
Credentials error during installation of magento/module-invitation

### ISSUE THREAD

**Issue by osd-henry** [magento/magento-cloud#449]
Hello,
This is the first time we use Magento Cloud for our company, and we're stuck at `composer install`'s credentials error for only `magento/module-invitation` (the other `magento-` packages work fine):
```
Package operations: 364 installs, 0 updates, 0 removals
  - Installing magento/module-invitation (100.3.4): Downloading (connecting...)
                                                                                                                  
  [Composer\Downloader\TransportException]                                                                        
  Invalid credentials for 'https://repo.magento.com/archives/magento/module-invitation/magento-module-invitatio   
  n-100.3.4.0.zip', aborting.
```
The auth keys we used are from our sandbox account at https://marketplace.magento.com/customer/accessKeys/. I've searched of the older issues from your repo but unfortunately couldn't fix it.

I'm looking forward for your kind reply.
Thank you

**Comment by YPyltiai** [comment]
Hi @osd-henry,

Do you have Enterprise license entitlements on your keys?
This error is pretty much about you having no access to download the package, meaning your keys do not work properly. Since it fails on the very first module, it looks like something is wrong with them in general (not even enterprise-related likely).

May you please check the keys once again?

Thanks,
Yevhenii

**Comment by osd-henry** [comment]
Hi @YPyltiai,

Thanks for response. Actually this a sandbox environment Magento team sent to us, claimed it to be EE / Cloud edition. I can access https://accounts.magento.cloud/ using provided account.

Furthermore, since we tried to install many times, the installation continue progress from the last failed try. The full log after I remove composer `vendor` folder and try again should be:

```
  ...
  - Installing magento/framework-bulk (100.3.4): Loading from cache
  - Installing magento/module-asynchronous-operations (100.3.4): Loading from cache
  - Installing magento/module-deploy (100.3.4): Loading from cache
  - Installing magento/module-cron (100.3.4): Loading from cache
  - Installing magento/module-developer (100.3.4): Loading from cache
  - Installing magento/module-translation (100.3.4): Loading from cache
  - Installing magento/module-backup (100.3.4): Loading from cache
  - Installing magento/module-vault (101.1.4): Loading from cache
  - Installing magento/module-instant-purchase (100.3.4): Loading from cache
  - Installing magento/module-paypal (100.3.4): Loading from cache
  - Installing magento/module-checkout-agreements (100.3.4): Loading from cache
  - Installing amzn/amazon-pay-sdk-php (3.6.0): Loading from cache
  - Installing amzn/amazon-pay-and-login-with-amazon-core-module (3.3.1): Loading from cache
  - Installing amzn/login-with-amazon-module (3.3.1): Loading from cache
  - Installing amzn/amazon-pay-module (3.3.1): Loading from cache
  - Installing bacon/bacon-qr-code (1.0.3): Loading from cache
  - Installing magento/module-send-friend (100.3.4): Loading from cache
  - Installing magento/module-grouped-product (100.3.4): Loading from cache
  - Installing magento/module-configurable-product (100.3.4): Loading from cache
  - Installing dotmailer/dotmailer-magento2-extension (4.1.0): Loading from cache
  - Installing dotmailer/dotmailer-magento2-extension-chat (1.0.0): Loading from cache
  - Installing magento/module-invitation (100.3.4): Downloading (connecting...)
                                                                                                                  
  [Composer\Downloader\TransportException]                                                                        
  Invalid credentials for 'https://repo.magento.com/archives/magento/module-invitation/magento-module-invitatio   
  n-100.3.4.0.zip', aborting.
```
As you can see, the other `magento/...` packages work fine so I don't think it's keys related issue. Please correct me if I'm wrong but we're nearly stuck at this point for about 3 days and the sad part is our website is nowhere to be deployed nor running.

**Comment by NadiyaS** [comment]
Hi @osd-henry,
All modules which were installed before - CE Magento modules,
where **magento/module-invitation** is the first Magento EE module installed by composer. To check that the problem exactly in access to EE, you may change composer.json to not install this module:
```
"replace": {
    "magento/module-invitation": "*"
}
```
And after this run `composer update`. You will see that you have the same problem with next EE module, e.g. **magento/module-reward**.

**Comment by osd-henry** [comment]
Hi @NadiyaS ,
Do you know how to deal with this issue? Since we got this error on https://accounts.magento.cloud/, hence the sandbox environment wasn't able to be deployed and was unusable. The account is expeced to work since it was provided by Magento team. I guess there must be some workarounds.

**Comment by NadiyaS** [comment]
@osd-henry ,
I would recommend talking to those who provided this account to you.
I do not know how your project was configured, but please check keys from auth.json file in your project. And if you have at least one successful deployment, it means that those keys work (or at least worked on that moment).

**Comment by osd-henry** [comment]
@NadiyaS Well, we received this account, then tried to access the websites listed in the project, but they all returned `404 No route found for ***.us-4.magentosite.cloud`, then I found some lines from build log like:

```
- Magento Cloud Bot created a new project Project Title                   Success
- Marketplacer Cloud changed project name to ***                          Success
- Marketplacer Cloud initialized environment Master with profile          Failure
Magento Enterprise Cloud Edition 
```
As you can see, the very third step of project setup automation already raised authentication error (I clicked on the Failure link to figure out what's going wrong). We're trying to reach our contact at Magento for supports since it has been over a week and we're still no where near a usable setup for our site.

**Comment by NadiyaS** [comment]
@osd-henry 
Unfortunately, there is nothing we can help you here. Problem with access should be solved through a support ticket or directly with those who provided that environment to you.

**Comment by osd-henry** [comment]
Thanks for all your kind support. I've got contacted from Magento and it turned out we were lack of EE permissions for our keys. It works fine now so I'm gonna close this issue.

**Comment by stuartfranke** [comment]
For anyone else coming here with a similar issue, for me it was a case of generating new keys in marketplace.magento.com *after* I received Enterprise access
