### ISSUE TITLE
Local install fails during composer install with magento/module-invitation

### ISSUE THREAD

**Issue by mkrell-miles** [magento/magento-cloud#450]
I'm trying to install Magento 2.3 on a local Laragon install from Magneto-cloud, but the composer install is failing because of this error:

```
  [Composer\Downloader\TransportException]
  Invalid credentials for 'https://repo.magento.com/archives/magento/module-invitation/magento-module-invitation-100.3.4.0.zip', aborting.
```

I've tried re-generating my marketplace access keys and tried using another account. Adobe is saying their servers are working fine from what I can tell. I've ensured that I'm putting the public key in the "username" prompt and the private key in the "password" prompt. I'm not saving my keys anywhere and am putting them in every time it asks.

~ Matt

**Comment by NadiyaS** [comment]
Hi @mkrell-miles,

We apologize for the late response. 
I believe that you already solve the issue with keys as this error is definitely is about the lack of permissions for Enterprise Edition. 
This type of problem should be reported to account manager or you need to create a support ticket.

I close this issue as there is nothing to do from the cloud template side.

**Comment by mkrell-miles** [comment]
@NadiyaS yeah that definitely was the issue. Thx
