### ISSUE TITLE
FEAT: Opcache cron 

### ISSUE THREAD

**Issue by damienwebdev** [magento/magento-cloud#513]
Whatever backing infra belies the Cloud for storage has some nasty latency, as several of my perf issues and CPU consumption problems come from `cron:run` as a result of `includeFile` (resulting in an `include`).

As a result, I asked myself why? Why are you calling `includeFile` so often?

The answer to this question is that `cron:run` is called from a CLI context, where `opcache` is essentially disabled.

As such, all the awesome perf benefits of `opcache` are disabled in the cron context as currently configured by cloud.

Now, someone may naively recommend `opcache.enable_cli` -- this would be a mistake. `opcache.enable_cli` caching only applies within the context of a single run of a cli command (the cache is lost when the command completes).

We'd need a way to store the result of the `opcache` during a `cron:run` and then reload it once we start the next run. 

Any chance that we can store the `opcache` for `cron` in `tmpfs` or on disk?

This would update the `.magento.app.yaml` to something like:

```yaml
# Default Magento 2 cron jobs
crons:
    cronrun:
        spec: "* * * * *"
        cmd: |
           php \
	     -d opcache.file_cache_only=1 \
	     -d opcache.enable_cli=1 \
	     -d opcache.file_cache=/mnt/tmpfs \
	     -d memory_limit=-1 \
	     bin/magento cron:run
```
or

```yaml
# Default Magento 2 cron jobs
crons:
    cronrun:
        spec: "* * * * *"
        cmd: |
           php \
	     -d opcache.file_cache_only=1 \
	     -d opcache.enable_cli=1 \
	     -d opcache.file_cache=/mnt/disk-any-where-just-let-me-mount-something-so-i-dont-recompile-on-every-cron-run \
	     -d memory_limit=-1 \
	     bin/magento cron:run
```
cc: @shiftedreality

**Comment by NadiyaS** [comment]
Hi @damienwebdev,
thank you for reporting about this issue.
Internal ticket for investigation is MCLOUD-7103

**Comment by jordanvector** [comment]
@NadiyaS Did anything ever come from this?
