### ISSUE TITLE
[PAGE BUILDER] Children elements disappearing

### ISSUE THREAD

**Issue by Axel29** [magento/magento-cloud#514]
When saving a custom content type that has children, it's children completely disappear from the component in the admin.
The bug only occurs when the `<render args="masterTemplate" />` line is surrouned by a `div` **and** that there are elements **after** that render tag.

You can find a modified version of [Example PageBuilderFaq official demo](https://github.com/magento-devdocs/pagebuilder-examples/tree/master/Example/PageBuilderFaq) at [this URL](https://github.com/magento/magento2/files/5366510/Example_PageBuilderFaq.zip) with only an input text added to the Content Type and a div surrounding the `<render args="masterTemplate" />` in the master.html file.

I've tried contacting the support but apparently it's considered as "out of the scope" since it's about a new Content Type, even if all I did was trying to add a simple input text to an official Page Builder Content Type...

### Preconditions (*)

1. Magento Cloud 2.3.4 (not testing on higher versions)

### Steps to reproduce (*)

1. Create a content type with children
2. In the `master.html` template, surround the `<render args="masterTemplate" />` line with a `div` tag.
3. Add any kind of element (for example an input text) after that div
4. Go to the admin and add this content type to a page and fill it completely
5. Save the page

### Expected result (*)

1. The content type is saved and everything inside it is visible on both frontend and backend.
2. The admin can edit that content type

### Actual result (*)

1. The content type is correctly saved
2. The content is visible on frontend
3. The children are completely missing from the content type in the admin.

---

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**Comment by NadiyaS** [comment]
Hi @Axel29 ,

this issue is not related to Magento cloud templates. It should be transferred to [magento/magento2](https://github.com/magento/magento2)

**Comment by YPyltiai** [comment]
Closing per @NadiyaS's comment. @Axel29 , please copy it to magento/magento2 as we cannot move it now.
