### ISSUE TITLE
[Web UI] Cloud Web UI w/ Github Integration repeats the same environment ad infinitum

### ISSUE THREAD

**Issue by damienwebdev** [magento/magento-cloud#515]
![Annotation 2020-11-10 092133](https://user-images.githubusercontent.com/9029654/98712487-5f6aec80-2354-11eb-9554-da5e01a503c7.png)

Essentially, the title. But, in essence, tons of duplicate tasks become "pending" and the number of these tasks increases the more PRs we add.

**Comment by damienwebdev** [comment]
cc: @YPyltiai

**Comment by gamort** [comment]
Exclude pull requests from your syncs.

See https://devdocs.magento.com/cloud/integrations/github-integration.html

Use --build-pull-requests=false

Note: this same option is available for Bitbucket but it is not listed in the documentation...  I guess I should fix that since I noticed.

**Comment by damienwebdev** [comment]
@gamort what if we WANT to build PRs? I just don't want the duped logs.

**Comment by gamort** [comment]
You can use integration:update so you don't have to recreate the entire thing:

magento-cloud integration:list
lookup ID

magento-cloud integration:update [ID] --build-pull-requests=false

What I personally would love to see working is:  --environments=ENVIRONMENTS.  So I can limit it to just the branches master, production, staging, and integration

**Comment by damienwebdev** [comment]
Oh, so you're saying EVERY PR is re-building every other PRs enviroments?

**Comment by YPyltiai** [comment]
It looks like a bug to me though - let me send it over to the team to look why this happens.

**Comment by damienwebdev** [comment]
Closed.
