### ISSUE TITLE
Add compression to Magento-cloud scp command

### ISSUE THREAD

**Issue by nbennett25** [magento/magento-cloud#517]
Hi - we use the `magento-cloud scp` command to copy down images from the remote pub/media directory, but it takes a loooong time - is it possible to add the scp compression flag (-C) to the magento cloud version? If there is a better/dedicated tool to download the media directory (similar to db:dump..?) that would also be helpful.

**Comment by YPyltiai** [comment]
Hi @nbennett25 , you could run scp command with the flag you need through SSH. Unfortunately there is no possibility to add this to magento-cloud CLI at this time.

Thanks!
