### ISSUE TITLE
magento-module-staging-page-builder-2.1.0.0.zip" file could not be downloaded 

### ISSUE THREAD

**Issue by cristiano-pacheco** [magento/magento-cloud#518]
Hi, I'm working in a Magento Cloud project and since last friday 2020-01-15, we have receiving the composer error below:

  [Composer\Downloader\TransportException]                                                                                                                                           
  The "https://repo.magento.com/archives/magento/module-staging-page-builder/magento-module-staging-page-builder-2.1.0.0.zip" file could not be downloaded (HTTP/1.1 404 Not Found) 

![composer-error](https://user-images.githubusercontent.com/5084933/105352351-8c494480-5bcc-11eb-990b-8f627c9ed4f7.png)

  
There is no problema with credentials, all other packages are installed successfully.

Could you help us? please.

**Comment by YPyltiai** [comment]
@cristiano-pacheco ,

I shared this case with our repo team and they indicated the problem is with keys based on the error you get.
This may need a Support ticket into Zendesk to get resolved, as we need to look at your MageID and repo keys to help.

Thanks!

**Comment by cristiano-pacheco** [comment]
Thanks for the feedback, resolved.

**Comment by ueltonVeslei** [comment]
> @cristiano-pacheco ,
> 
> I shared this case with our repo team and they indicated the problem is with keys based on the error you get.
> This may need a Support ticket into Zendesk to get resolved, as we need to look at your MageID and repo keys to help.
> 
> Thanks!

I have the same problem, can I do something without a ticket?

**Comment by ueltonVeslei** [comment]
@shwetsonly You need to have authentication keys as a Adobe Partner or Paid Client: https://devdocs.magento.com/guides/v2.3/install-gde/prereq/connect-auth.html

https://devdocs.magento.com/cloud/setup/first-time-setup-import-prepare.html#auth-json

In my case the issue is caused by incorrect permissions on WSL 2.
