### ISSUE TITLE
Services are not upgrading automatically

### ISSUE THREAD

**Issue by Stoyvo** [magento/magento-cloud#519]
Reference: https://github.com/magento/magento-cloud/blob/8d721b16a5141b6a113d40f49e3173ecfed7a3b8/.magento/services.yaml#L3

Today an Adobe CSR reached out to notify that services are not upgraded in our environments, regardless of having these configuration values provided. This comment communicates that services in this file will reflect the environment, however this is not true according.

Please provide clear messaging in this services.yaml file, CSR could not tell us if this comment hold true to Pro or Non-Pro cloud projects.

**Comment by YPyltiai** [comment]
Hi @Stoyvo, this file works on containerized environments only, so Integration ones and Starter projects.
Pro has a different architecture and as of now is not controlled by this file. 

It is explained on DevDocs over here: https://devdocs.magento.com/cloud/project/services.html - there is a note saying that for PRO projects the process is  different.

**Comment by Stoyvo** [comment]
Sounds great @YPyltiai - Please update this file with a link to the documentation, the services.yaml is horribly deceiving and incorrectly documenting functionality.
