### ISSUE TITLE
Where is pub/front-static.php?

### ISSUE THREAD

**Issue by 7ochem** [magento/magento-cloud#8]
The [`.magento.app.yaml`](https://github.com/magento/magento-cloud/blob/master/.magento.app.yaml#L57) is referencing a `pub/front-static.php` file. But I don't see it in `pub/`.

In previous versions it was physically present (see [2.0.4 `pub/` directory listing](https://github.com/magento/magento-cloud/tree/2.0.4/pub)). Also the `magento/magento-cloud-configuration` module is not creating it (or copying it from `pub/static.php`).

Looking at [the history](https://github.com/magento/magento-cloud/commits/master/pub/front-static.php), the file was removed in a mass removal commit "Remove files from base package from template" by @bwaters on Jul 26, 2016.

So, shouldn't it be there? Or is the line in the `.magento.app.yaml` not correct?

**Comment by mathiasschopmans** [comment]
I created a PR: https://github.com/magento/magento-cloud/pull/16

**Comment by shiftedreality** [comment]
This file is being copied from static.php. If you have any issues with this, please let us know. Closed
